### ISSUE TITLE
Subset of garmentnets.zarr dataset

### ISSUE THREAD

**Issue by lokender** [columbia-ai-robotics/garmentnets#1]
Thank you for this wonderful work. I want to make a request, can you please upload a small subset of garmentnets dataset containing some examples of each garment, so that we can try out your method. Currently, it is 682GB, which is huge.

Thanks in advance

**Comment by cheng-chi** [comment]
A 25 instance [small subset](https://github.com/columbia-ai-robotics/garmentnets#-sample-datasets) of the dataset has been added.
