### ISSUE TITLE
How to get the winding number field and point-to-point correspondence for new mesh data?

### ISSUE THREAD

**Issue by renyu2016** [columbia-ai-robotics/garmentnets#4]
Hi there! 
Thank you for releasing this fantastic work! I have a question, how can I generate the winding number field and point-to-point correspondence between sim space and NOCS space for new mesh data?   Is it possible that you could provide the code? Or maybe could you tell me the procedure to do this?
Thanks in advance!

**Comment by cheng-chi** [comment]
@renyu2016 Sorry for the delay, I have been working toward a publication deadline last week. The winding number field is created using [libigl](https://libigl.github.io/libigl-python-bindings/igl_docs/#fast_winding_number_for_meshes). Unfortunately to make the code parallelizable on our server, I did a lot of hacks and the code is quite messy, but writing you own generation code using this library shouldn't be that hard! NOCS space is defined by simply computing the larges bounding box of all meshes for a category, and then scale the bonding box to within 0 to 1 for all dimension, plus some padding.
